# monitoring/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-dashboard.yaml
  - grafana.yaml
  - loki.yaml
  - prometheus-stack.yaml
  - promtail.yaml
  - grafana-ingress.yml
