# clusters/my-cluster/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure
  - ../../secrets
  - ../../databases
  - ../../applications
  - ../../applications/nginx-ingress
