apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 404 =302 https://google.com;
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($status = 404) {
        return 302 https://google.com;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: wordpress.mnpspbd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
